
---
functional:
  - Пользователь должен иметь возможность создать свою учетную запись
  - Пользователь должен иметь возможность войти в систему, используя существующую учетную запись
  - Пользователь должен иметь возможность войти в систему, используя существующую учетную запись GitHub
  - Пользователь должен иметь возможность войти в систему, используя существующую учетную запись Discord
  - Пользователь должен иметь возможность попробовать демонстрационную игру без регистрации
  - Пользователь должен видеть главную страницу с кнопкой для создания новой игры
  - Пользователь должен иметь возможность смены основного языка программирования
  - Пользователь должен иметь возможность играть против бота
  - Пользователь должен иметь возможность пригласить друзей для игры используя ссылку
  - Пользователь должен иметь возможность участвовать в игре со случайными пользователями
  - При создании игры пользователь должен иметь возможность выбрать конкретную задачу из выпадающего списка доступных задач
  - При создании игры пользователь должен иметь возможность выбрать случайную задачу из всего списка доступных задач
  - При создании игры пользователь должен иметь возможность установить определенное время для решения задачи
  - Двум игрокам должна быть предоставлена возможность соревноваться друг с другом в решении задач
  - Два игрока должны видеть процесс написания кода друг друга в реальном времени
  - Во время соревнования должен отображаться таймер, показывающий оставшееся время
  - Во время совернования по истечении установленного времени система должна автоматически определять результат соревнования (победа, поражение или ничья) на основе успешного прохождения автотестов и скорости представленных решений
  - Система должна записывать и отображать время, затраченное каждым игроком на решение задачи
  - Сайт должен поддерживать организацию и проведение турниров
  - Пользователь должен иметь возможность создавать свои собственные турниры, настраивать параметры и приглашать других участников
  - Пользователь должен иметь возможность вступать в свои собственные и созданные другими пользователями турниры
  - Пользователь должен иметь возможность просматривать историю своих предыдущих игр, включая результаты и статистику
  - Пользователь должен иметь возможность просматривать свою текущую статистику, включая общее количество игр, количество побед, поражений и другие соответствующие показатели
  - Зарегистрированный пользователь должен иметь возможность писать в чат на странице сайта
non-functional:
  - Сайт должен быть удобным в использовании на мобильных устройствах с различными размерами экранов и разрешениями
  - Сайт должен быть безопасным и обеспечивать защиту пользовательских данных, использование HTTPS, шифрование данных, защита от SQL-инъекций
  - Сайт должен быть способен эффективно обрабатывать большое количество трафика (100 000 - 300 000 посещений в день) и одновременно работающих пользователей без ухудшения производительности
  - Пользователь может видеть задачи на двух языках — русском и английском
implicit:
  - Сайт должен обеспечивать высокую степень доступности по стандарту WCAG (Web Content Accessibility Guidelines), с минимальным временем простоя и минимизировать количество сбоев и ошибок во время игр
  - Сайт должен быть совместим с последними версиями популярных веб-браузеров, таких как Yandex, Chrome, Firefox, Safari и Edge
  - Сайт должен поддерживать несколько языков интерфейса, включая русский и английский
